name: vertview
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.1
  - pip
  - pip:
      - -r requirements.txt
      - -e .
